---
common_packages:
  debian:
    - apt-transport-https
    - build-essential
    - ca-certificates
    - curl
    - git
    - gnupg
    - htop
    - jq
    - libssl-dev
    - lsb-release
    - make
    - net-tools
    - python3-pip
    - software-properties-common
    - sudo
    - unzip
    - vim
    - wget
    - zsh
