---
- name: Install container utilities (Debian/Ubuntu)
  apt:
    name: "{{ container_utilities.debian }}"
    state: present
  when: ansible_os_family == 'Debian'
  tags: [containers, utilities]

- name: Install container utilities (RHEL/Rocky)
  dnf:
    name: "{{ container_utilities.redhat }}"
    state: present
  when: ansible_os_family == 'RedHat'
  tags: [containers, utilities]

- name: Install Dive
  get_url:
    url: "https://github.com/wagoodman/dive/releases/download/{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.tar.gz"
    dest: "/tmp/dive.tar.gz"
  register: dive_download
  tags: [containers, utilities]

- name: Extract and install Dive
  unarchive:
    src: "/tmp/dive.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: [--strip-components=1]
    mode: '0755'
  when: dive_download.changed
  tags: [containers, utilities]

- name: Install lazydocker
  get_url:
    url: "https://github.com/jesseduffield/lazydocker/releases/download/{{ lazydocker_version }}/lazydocker_{{ lazydocker_version }}_Linux_x86_64.tar.gz"
    dest: "/tmp/lazydocker.tar.gz"
  register: lazydocker_download
  tags: [containers, utilities]

- name: Extract and install lazydocker
  unarchive:
    src: "/tmp/lazydocker.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: [--strip-components=1]
    mode: '0755'
  when: lazydocker_download.changed
  tags: [containers, utilities]
