---
- name: Add Kubernetes repository (Debian/Ubuntu)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes
  when: ansible_os_family == 'Debian'
  tags: [containers, kubernetes]

- name: Add Kubernetes repository key (Debian/Ubuntu)
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: ansible_os_family == 'Debian'
  tags: [containers, kubernetes]

- name: Add Kubernetes repository (RHEL/Rocky)
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: 1
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  when: ansible_os_family == 'RedHat'
  tags: [containers, kubernetes]

- name: Install Kubernetes tools (Debian/Ubuntu)
  apt:
    name: "{{ kubernetes_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags: [containers, kubernetes]

- name: Install Kubernetes tools (RHEL/Rocky)
  dnf:
    name: "{{ kubernetes_packages }}"
    state: present
  when: ansible_os_family == 'RedHat'
  tags: [containers, kubernetes]

- name: Install k9s
  get_url:
    url: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
    dest: "/tmp/k9s.tar.gz"
  register: k9s_download
  tags: [containers, kubernetes]

- name: Extract and install k9s
  unarchive:
    src: "/tmp/k9s.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: [--strip-components=1]
    mode: '0755'
  when: k9s_download.changed
  tags: [containers, kubernetes]
