---
- name: Install container tools (Docker/Podman)
  include_tasks: install_docker.yml
  when: install_docker | bool
  tags: [containers, docker]

- name: Install Kubernetes tools
  include_tasks: install_kubernetes.yml
  when: install_kubernetes | bool
  tags: [containers, kubernetes]

- name: Install container utilities
  include_tasks: install_utilities.yml
  tags: [containers, utilities]
