---
- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_env.HOME }}/.config/nvim"
    - "{{ ansible_env.HOME }}/.ssh"

- name: Deploy .bashrc configuration
  template:
    src: bashrc.j2
    dest: "{{ ansible_env.HOME }}/.bashrc"
    backup: yes
    mode: '0644'

- name: Deploy .gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: '0644'

- name: Deploy git aliases
  template:
    src: git_aliases.j2
    dest: "{{ ansible_env.HOME }}/.git_aliases"
    mode: '0644'

- name: Deploy kubectl aliases
  template:
    src: kubectl_aliases.j2
    dest: "{{ ansible_env.HOME }}/.kubectl_aliases"
    mode: '0644'

- name: Deploy Starship configuration
  template:
    src: starship.toml.j2
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    mode: '0644'

- name: Deploy Neovim configuration
  template:
    src: init.vim.j2
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    mode: '0644'

- name: Source .bashrc in .profile
  lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    line: "source ~/.bashrc"
    create: yes
    state: present
