---
- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_env.HOME }}/.config/nvim"
    - "{{ ansible_env.HOME }}/.ssh"

- name: Deploy .bashrc configuration
  template:
    src: bashrc.j2
    dest: "{{ ansible_env.HOME }}/.bashrc"
    backup: yes
    mode: '0644'

- name: Deploy .gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: '0644'

- name: Deploy git aliases
  template:
    src: git_aliases.j2
    dest: "{{ ansible_env.HOME }}/.git_aliases"
    mode: '0644'

- name: Deploy kubectl aliases
  template:
    src: kubectl_aliases.j2
    dest: "{{ ansible_env.HOME }}/.kubectl_aliases"
    mode: '0644'

- name: Deploy Starship configuration
  template:
    src: starship.toml.j2
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    mode: '0644'

- name: Deploy Neovim configuration
  template:
    src: init.vim.j2
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    mode: '0644'

- name: Source .bashrc in .profile
  lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    line: "source ~/.bashrc"
    create: yes
    state: present

- name: Install VS Code (Debian/Ubuntu)
  block:
    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      become: yes
    
    - name: Add VS Code repository
      apt_repository:
        repo: "deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main"
        state: present
      become: yes
    
    - name: Install VS Code
      apt:
        name: code
        state: present
        update_cache: yes
      become: yes
  when: os_family == "debian"

- name: Install VS Code (RHEL/Rocky/CentOS)
  block:
    - name: Add Microsoft repository
      yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        enabled: yes
      become: yes
    
    - name: Install VS Code
      dnf:
        name: code
        state: present
      become: yes
  when: os_family == "redhat"

- name: Install Windsurf (if available)
  block:
    - name: Download Windsurf (Debian/Ubuntu)
      get_url:
        url: "https://windsurf-stable.codeiumdata.com/linux-x64/stable/windsurf-linux-x64-1.0.5.deb"
        dest: "{{ ansible_env.HOME }}/Downloads/installers/windsurf.deb"
        mode: '0644'
      when: os_family == "debian"
      ignore_errors: yes
    
    - name: Install Windsurf (Debian/Ubuntu)
      apt:
        deb: "{{ ansible_env.HOME }}/Downloads/installers/windsurf.deb"
        state: present
      become: yes
      when: os_family == "debian"
      ignore_errors: yes
